name: neurascan_ai
version: 1.0.0+1
description: Mobile-first Flutter prototype for NeuroScan AI.
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
